// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KoU8YyrSwRIjuhMczS8mnEBgMfDlrzc',
    appId: '1:504614396126:web:2d526051d5c7503e21224f',
    messagingSenderId: '504614396126',
    projectId: 'plataforma-examenes-f2df9',
    authDomain: 'plataforma-examenes-f2df9.firebaseapp.com',
    storageBucket: 'plataforma-examenes-f2df9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-LCVPrc_HfTYfpQPRY9nyItYgKcvMuc',
    appId: '1:504614396126:android:7acd6536849f059521224f',
    messagingSenderId: '504614396126',
    projectId: 'plataforma-examenes-f2df9',
    storageBucket: 'plataforma-examenes-f2df9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr6eJXDk-9LO9_l7tcBMnbGJ4pRZq0fDQ',
    appId: '1:504614396126:ios:ce1160573fd6601e21224f',
    messagingSenderId: '504614396126',
    projectId: 'plataforma-examenes-f2df9',
    storageBucket: 'plataforma-examenes-f2df9.firebasestorage.app',
    iosBundleId: 'com.example.appMovilSistemaExamenes',
  );
}
